name: CI

on: [push]
permissions:
  contents: write

jobs:
  ci:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: Install python dependencies
        run: pip install -r requirements.txt
      - name: Build
        run: python run.py
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          clean: true
          single-commit: true
